name: Electron CD

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
#         os: [windows-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: autofix eslint-errors
        run: |
          npm run fix
      - name: Build vue
        run: |
          npm run build
      - name: Build app
        run: |
          npm run dist
      - name: Cleanup artifacts
        run: |
          npx rimraf 'electron-dist/!(*.exe|*.deb|*.AppImage|*.dmg)'
        shell: bash
        if: matrix.os != 'windows-latest'
      - name: Cleanup artifacts windows
        run: |
          npx rimraf 'electron-dist\!(*.exe|*.deb|*.AppImage|*.dmg)'
        if: matrix.os == 'windows-latest'
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "electron-dist/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
